/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "claves_inter.h"

bool_t
xdr_double_array (XDR *xdrs, double_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->double_array_val, (u_int *) &objp->double_array_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_KeyValue (XDR *xdrs, KeyValue *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_double_array (xdrs, &objp->V_value2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_d_set_value_1_argument (XDR *xdrs, d_set_value_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_double_array (xdrs, &objp->arg4))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_d_modify_value_1_argument (XDR *xdrs, d_modify_value_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_double_array (xdrs, &objp->arg4))
		 return FALSE;
	return TRUE;
}
