
# This is a template Makefile generated by rpcgen

# Parameters

BIN_FILES = servidor cliente 
CC = gcc
CFLAGS = -Wall -fPIC -g -I/usr/include/tirpc
DEPS = claves.h list.h claves_inter.h
OBJ = servidor.o cliente.o claves.o list.o claves_inter_xdr.o claves_inter_clnt.o claves_inter_svc.o

CPPFLAGS = -I$(INSTALL_PATH)/include
LDFLAGS = -L$(INSTALL_PATH)/lib/
LDLIBS = -lnsl -lpthread -ldl -ltirpc -lm

all: $(BIN_FILES) libclaves.so

servidor: servidor.o libclaves.so claves_inter_svc.o claves_inter_xdr.o 
	$(CC) -o $@ $^ $(CFLAGS) $(LDLIBS)
cliente: cliente.o libclaves.so
	$(CC) -o $@ $^ $(CFLAGS) $(LDLIBS)

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

libclaves.so: claves.o claves_inter_xdr.o claves_inter_clnt.o
	$(CC) -shared -o $@ $^ $(CFLAGS)

clean:
	rm -f $(BIN_FILES) *.o libclaves.so

.PHONY: all clean


