/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "claves_inter.h"
#include "claves.h"
#include "./lista/list.h"
#include "./lista/list.c"

List my_list;
int iniciado;
bool_t
d_init_1_svc(int *result, struct svc_req *rqstp)
{
	bool_t retval;
    retval = TRUE;
	*result = iniciar(&my_list);

	return retval;
}

bool_t
d_set_value_1_svc(struct KeyValue arg1, int *result,  struct svc_req *rqstp)
{
	bool_t retval;
	
	/*
	 * insert server code here
	 */

	return retval;
}

bool_t
d_get_value_1_svc(int key, struct KeyValue *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

bool_t
d_modify_value_1_svc(struct KeyValue arg1, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

bool_t
d_delete_key_1_svc(int key, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

bool_t
d_exist_1_svc(int key, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

int
key_value_service_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
